$(GENOBJC): $(SRC)

$(SRC): $(GENSRC)

$(GENSRC):
	mkdir $(BINDIR)/$(MODULE) && cd $(BINDIR)/$(MODULE) && \
		$(WOT_TD_GEN) --appdir $(APPDIR) --board $(BOARD) --used_modules $(USEMODULE) --thing_models $(WOT_THING_MODELS) --thing_instance_info $(WOT_INSTANCE_INFO) --output_path $(WOT_TD_CONFIG)
