$(SRC): $(GENSRC)

$(GENSRC):
	$(Q)D=$(BINDIR)/$(MODULE) && \
		mkdir -p "$$D" && \
			cd $(CURDIR) && \
				$(WOT_TD_GEN) --appdir $(APPDIR) --board $(BOARD) --used_modules $(USEMODULE) --thing_models $(WOT_THING_MODELS) --thing_instance_info $(WOT_INSTANCE_INFO) --output_path $(WOT_TD_CONFIG)